
host: '172.23.0.200'
port: 50054
name: 'order-srv'
tags:
  - 'order-srv'
  - 'shop'
  - 'dev'

##########################
###     mysql 配置      ###
##########################
mysql:
  host: 'local.docker.node1.com'
  port: 3306
  db: 'micro_order_srv'
  user: 'root'
  password: '123456'

##########################
### 注册中心 consul 配置 ###
##########################
consul:
  host: 'local.docker.node1.com'
  port: 8500

##########################
###       服务配置       ###
##########################
goods_srv:
  name: 'goods-srv'
inventory_srv:
  name: 'inventory-srv'

##########################
###    RocketMQ 配置    ###
##########################
rocket-mq:
  host: '192.168.56.110'
  port: 9876
  order_reback_topic: 'order_reback'
  order_timeout_topic: 'order_timeout'

##########################
### 链路追踪 jaeger 配置 ###
##########################
jaeger:
  host: '192.168.56.110'
  port: 6831