
name: 'goods-srv'
host: 'localhost'

##########################
###     mysql 配置      ###
##########################
mysql:
  host: 'local.docker.node1.com'
  port: 3306
  db: 'micro_goods_srv'
  user: 'root'
  password: '123456'

##########################
### 注册中心 consul 配置 ###
##########################
consul:
  host: 'local.docker.node1.com'
  port: 8500
  tags:
    - 'goods-srv'
    - 'shop'