
host: '172.23.0.200'
port: 50052
name: 'goods-srv'
tags:
  - 'goods-srv'
  - 'shop'
  - 'dev'

##########################
###     mysql 配置      ###
##########################
mysql:
  host: 'local.docker.node1.com'
  port: 3306
  db: 'micro_goods_srv'
  user: 'root'
  password: '123456'

##########################
### 注册中心 consul 配置 ###
##########################
consul:
  host: 'local.docker.node1.com'
  port: 8500

##########################
###    elastic 配置     ###
##########################
elastic:
  host: 'local.docker.node1.com'
  port: 9200